name: Safe Sync with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间午夜执行一次
  workflow_dispatch: {}  # 允许手动触发

jobs:
  safe-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # 确保拉取完整历史

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/yonggekkk/sing-box-yg.git || echo "upstream already exists"
          git fetch upstream

      - name: Merge upstream/main into main
        run: |
          git checkout main
          git merge --no-commit --no-ff upstream/main || echo "Merge conflicts detected, skipping push"
          git commit -m "Sync with upstream" || echo "Nothing to commit"
          git push origin main || echo "Nothing to push"
